'use client'

import { useEffect, useMemo, useState } from 'react'
import { jsPDF } from 'jspdf'
import { Check, ChevronLeft, ChevronRight, Download, FileText, ShieldCheck } from 'lucide-react'

type Field = { id: string; label: string; type?: 'text' | 'textarea' | 'date' | 'choice'; options?: string[]; required?: boolean }
type Section = { title: string; description: string; fields: Field[] }

const sections: Section[] = [
  { title: 'Company & branding', description: 'Details used on declarations, reports and generated documents.', fields: [
    {id:'legalName',label:'Legal company name',required:true},{id:'addressEn',label:'Full company address in English',type:'textarea',required:true},{id:'addressAr',label:'Full company address in Arabic',type:'textarea'},{id:'phone',label:'Official telephone number',required:true},{id:'email',label:'Official company email',required:true},{id:'tradeLicense',label:'Trade licence number'},{id:'saifRegistration',label:'SAIF Zone registration number'},{id:'customsCode',label:'Customs code / importer code'},{id:'currency',label:'Default currency',type:'choice',options:['AED','USD','EUR','Other']},{id:'documentsLanguage',label:'Generated document language',type:'choice',options:['English','Arabic','Bilingual English and Arabic'],required:true}]},
  { title: 'Users & access', description: 'Define initial users and security rules. Attach the detailed user list with the final PDF.', fields: [
    {id:'firstAdmin',label:'First System Administrator — full name and company email',required:true},{id:'userList',label:'List each user: Full name | Email | Department | Role | Language | Email alerts | WhatsApp alerts | Mobile',type:'textarea',required:true},{id:'multipleRoles',label:'Can one user have multiple roles?',type:'choice',options:['Yes','No']},{id:'mfa',label:'Require multi-factor authentication for administrators?',type:'choice',options:['Yes','No'],required:true},{id:'sessionTimeout',label:'Inactivity logout time',type:'choice',options:['15 minutes','30 minutes','60 minutes','Other']},{id:'userAdmin',label:'Who may create, deactivate and unlock users?'}]},
  { title: 'Approval workflow', description: 'Confirm declaration approval, amendment and escalation rules.', fields: [
    {id:'gmThreshold',label:'General Manager approval threshold in AED',required:true},{id:'thresholdBasis',label:'Threshold basis',type:'choice',options:['Invoice value','Customs value','Total landed value','Duty and VAT amount','Other']},{id:'financeZero',label:'Finance approval required when duty and VAT are zero?',type:'choice',options:['Yes','No']},{id:'returnReason',label:'Mandatory reason when returning or rejecting?',type:'choice',options:['Yes','No']},{id:'cancelRole',label:'Who can cancel a declaration?'},{id:'reapproval',label:'Does an amendment require the full approval workflow again?',type:'choice',options:['Yes','No']},{id:'numberFormat',label:'Declaration numbering format (example: IMP-2026-000001)'},{id:'approvalSla',label:'Approval SLA and escalation recipients for each level',type:'textarea'}]},
  { title: 'Duty, VAT & guarantees', description: 'Calculation, exchange-rate, guarantee and refund configuration.', fields: [
    {id:'dutyRate',label:'Default customs duty rate',required:true},{id:'vatRate',label:'Default VAT rate',required:true},{id:'dutyBasis',label:'Duty calculation basis',type:'choice',options:['CIF value','Customs value entered by user','Invoice value','Other']},{id:'vatBasis',label:'VAT calculation basis',type:'choice',options:['Customs value + duty','Invoice value','Other']},{id:'exchangeSource',label:'Exchange-rate source',type:'choice',options:['UAE Central Bank','Manual entry','Tally','Other']},{id:'guaranteeRule',label:'Guarantee utilization and release rules',type:'textarea'},{id:'guaranteeWarnings',label:'Low-balance and expiry warning thresholds'},{id:'refundWorkflow',label:'Duty-refund approval stages and required documents',type:'textarea'}]},
  { title: 'Operations & warehouse', description: 'Shipment, container, stock, gate-pass, inspection and hold rules.', fields: [
    {id:'warehouse',label:'Main warehouse name and code',required:true},{id:'ports',label:'Ports, airports and border points normally used',type:'textarea'},{id:'carriers',label:'Regular carriers, shipping lines and transport companies',type:'textarea'},{id:'freeDays',label:'Container free-day and detention/demurrage rules',type:'textarea'},{id:'stockPosting',label:'When should warehouse stock be posted?',type:'choice',options:['Cargo arrival','Warehouse receipt','Customs clearance','Inspection completion','Other']},{id:'tempTransfer',label:'Temporary-transfer return period and reminders'},{id:'gatePass',label:'Gate-pass numbering, issue, confirmation, closure and cancellation rules',type:'textarea'},{id:'inspection',label:'Inspection types, statuses and responsible roles',type:'textarea'},{id:'holds',label:'Hold categories, release approval and escalation rules',type:'textarea'}]},
  { title: 'Documents & reports', description: 'Printed outputs, attachments, QR verification and scheduled reports.', fields: [
    {id:'pdfLanguage',label:'PDF output language',type:'choice',options:['English','Arabic','Bilingual']},{id:'qrDocs',label:'Documents requiring QR/barcodes and what they should verify',type:'textarea'},{id:'signatures',label:'Documents requiring signature, stamp or letterhead',type:'textarea'},{id:'uploadRules',label:'Maximum upload size and allowed formats'},{id:'versioning',label:'Uploaded document replacement rule',type:'choice',options:['New version only','Replace with audit history','Replace without history']},{id:'expiry',label:'Permit/document expiry reminder schedule'},{id:'reports',label:'Required report samples, filters, schedules and recipients',type:'textarea',required:true},{id:'snapshots',label:'Store generated reports as fixed historical snapshots?',type:'choice',options:['Yes','No']}]},
  { title: 'Email, WhatsApp & Tally', description: 'Non-secret integration information. Never enter passwords or access tokens.', fields: [
    {id:'emailProvider',label:'Company email provider',type:'choice',options:['Microsoft 365 / Outlook','Google Workspace / Gmail','Standard SMTP','Other'],required:true},{id:'senderEmail',label:'Notification sender and reply-to email'},{id:'emailEvents',label:'Email events, receiving roles and escalation schedule',type:'textarea'},{id:'whatsappStatus',label:'WhatsApp setup status',type:'choice',options:['Meta Business ready','Meta verification in progress','Existing approved provider','Not configured']},{id:'whatsappNumber',label:'Company WhatsApp number (do not provide tokens)'},{id:'whatsappEvents',label:'Urgent WhatsApp events, recipients and preferred language',type:'textarea'},{id:'tallyVersion',label:'Tally product, version and hosting location'},{id:'tallyMapping',label:'Voucher types, ledger names, cost centres and transactions to export',type:'textarea'}]},
  { title: 'Data migration', description: 'Describe every legacy source. Do not send production secrets with this form.', fields: [
    {id:'migrationFiles',label:'For each source: File name | Description | Owner | Rows | Date range | Language | Must migrate | Known problems',type:'textarea',required:true},{id:'historyDate',label:'Earliest historical date to migrate',type:'date'},{id:'openingDate',label:'Required opening-balance date',type:'date'},{id:'closedData',label:'Migrate closed and cancelled declarations?',type:'choice',options:['Both closed and cancelled','Closed only','Neither']},{id:'linkedDocs',label:'Are documents linked using declaration numbers?',type:'choice',options:['Yes','No','Partially']},{id:'differences',label:'Known duplicates, inconsistent codes or stock differences',type:'textarea'},{id:'dataApprover',label:'Who approves corrections and signs final reconciliation?',required:true},{id:'secureTransfer',label:'Preferred secure final-data transfer method',type:'choice',options:['Client encrypted folder','Secure cloud transfer','Encrypted drive','Agree later']}]},
  { title: 'Security, UAT & acceptance', description: 'Backup, testing, training and final sign-off information.', fields: [
    {id:'retention',label:'Required retention period',type:'choice',options:['Five years','Longer than five years']},{id:'backup',label:'Required backup frequency',type:'choice',options:['Every 6 hours','Daily','Daily plus weekly archive','Other']},{id:'rpo',label:'Maximum acceptable data loss',type:'choice',options:['1 hour','6 hours','24 hours','Other']},{id:'uatTeam',label:'UAT coordinator and department testers with company emails',type:'textarea',required:true},{id:'uatStart',label:'Preferred UAT start date',type:'date'},{id:'goLive',label:'Preferred go-live period'},{id:'parallel',label:'Parallel operation period',type:'choice',options:['1 week','2 weeks','1 month','Other']},{id:'training',label:'Training method and language',type:'choice',options:['Remote — English','Remote — bilingual','On-site — English','On-site — bilingual','Both']},{id:'signatory',label:'Person authorized to sign final acceptance',required:true},{id:'acceptance',label:'Mandatory acceptance conditions and post-launch support expectations',type:'textarea'}]},
  { title: 'Client confirmation', description: 'Review the information and confirm it is accurate before generating the PDF.', fields: [
    {id:'confirmName',label:'Name',required:true},{id:'confirmTitle',label:'Job title',required:true},{id:'confirmDepartment',label:'Department'},{id:'confirmEmail',label:'Email',required:true},{id:'confirmDate',label:'Date',type:'date',required:true},{id:'confirmation',label:'I confirm the supplied information is accurate and may be used to configure and test the system.',type:'choice',options:['I confirm'],required:true}]},
]

const STORAGE_KEY = 'euro-customs-client-requirements-v1'

export function ClientRequirementsForm() {
  const [step,setStep]=useState(0)
  const [answers,setAnswers]=useState<Record<string,string>>({})
  const [ready,setReady]=useState(false)
  useEffect(()=>{try{const saved=window.localStorage.getItem(STORAGE_KEY);if(saved)setAnswers(JSON.parse(saved))}finally{setReady(true)}},[])
  useEffect(()=>{if(ready)window.localStorage.setItem(STORAGE_KEY,JSON.stringify(answers))},[answers,ready])
  const required=useMemo(()=>sections.flatMap(s=>s.fields.filter(f=>f.required)),[])
  const complete=required.filter(f=>answers[f.id]?.trim()).length
  const progress=Math.round((complete/required.length)*100)
  const current=sections[step]
  const set=(id:string,value:string)=>setAnswers(a=>({...a,[id]:value}))
  const generatePdf=()=>{
    const missing=required.filter(f=>!answers[f.id]?.trim())
    if(missing.length){alert(`Please complete ${missing.length} required field(s) before generating the PDF.`);return}
    const pdf=new jsPDF({unit:'mm',format:'a4'});const width=170;let y=18
    const line=(text:string,size=10,bold=false)=>{pdf.setFont('helvetica',bold?'bold':'normal');pdf.setFontSize(size);const rows=pdf.splitTextToSize(text||'Not provided',width);if(y+rows.length*5>282){pdf.addPage();y=18}pdf.text(rows,20,y);y+=rows.length*5+2}
    line('EURO TROUSERS MFG. CO. (FZC)',16,true);line('Customs & Warehouse Management System',12,true);line('Final Configuration, Migration and UAT Requirements',11);y+=3
    sections.forEach((section,index)=>{if(y>260){pdf.addPage();y=18}line(`${index+1}. ${section.title}`,13,true);section.fields.forEach(field=>{line(field.label,9,true);line(answers[field.id]||'Not provided',10);y+=1});y+=3})
    pdf.save(`EURO-TROUSERS-Client-Requirements-${answers.confirmDate||new Date().toISOString().slice(0,10)}.pdf`)
  }
  return <main className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border bg-card"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6 px-5 py-5 lg:px-8"><div><p className="font-mono text-xs font-semibold tracking-[.18em] text-primary">EURO TROUSERS MFG. CO. (FZC)</p><h1 className="mt-1 text-xl font-semibold text-balance">Customs system requirements</h1></div><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><ShieldCheck className="size-4"/>Private to this browser</div></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 px-5 py-8 lg:grid-cols-[260px_1fr] lg:px-8">
      <aside className="rounded-xl border border-border bg-card p-4 lg:sticky lg:top-6 lg:h-fit"><div className="mb-5"><div className="flex justify-between text-sm"><span>Required fields</span><strong>{progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${progress}%`}}/></div><p className="mt-2 text-xs text-muted-foreground">Answers save automatically on this device.</p></div><nav className="flex gap-2 overflow-x-auto lg:flex-col" aria-label="Questionnaire sections">{sections.map((s,i)=><button key={s.title} onClick={()=>setStep(i)} className={`min-w-48 rounded-lg px-3 py-2 text-left text-sm transition-colors lg:min-w-0 ${i===step?'bg-primary text-primary-foreground':'hover:bg-muted'}`}><span className="mr-2 font-mono text-xs">{String(i+1).padStart(2,'0')}</span>{s.title}</button>)}</nav></aside>
      <section className="rounded-xl border border-border bg-card shadow-sm"><div className="border-b border-border p-6 md:p-8"><p className="font-mono text-xs font-semibold uppercase tracking-wider text-primary">Section {step+1} of {sections.length}</p><h2 className="mt-2 text-2xl font-semibold text-balance">{current.title}</h2><p className="mt-2 max-w-2xl leading-relaxed text-muted-foreground">{current.description}</p>{step===6&&<div className="mt-4 rounded-lg border border-border bg-muted p-4 text-sm"><strong>Security notice:</strong> Do not enter passwords, API tokens, private keys or banking credentials.</div>}</div>
      <div className="grid gap-6 p-6 md:p-8">{current.fields.map(field=><label key={field.id} className="grid gap-2 text-sm font-medium">{field.label}{field.required&&<span className="sr-only">Required</span>}{field.type==='textarea'?<textarea rows={5} value={answers[field.id]||''} onChange={e=>set(field.id,e.target.value)} className="rounded-lg border border-input bg-background px-3 py-3 font-normal leading-relaxed outline-none focus:ring-2 focus:ring-ring" required={field.required}/>:field.type==='choice'?<select value={answers[field.id]||''} onChange={e=>set(field.id,e.target.value)} className="h-11 rounded-lg border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" required={field.required}><option value="">Select an option</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={field.type==='date'?'date':'text'} value={answers[field.id]||''} onChange={e=>set(field.id,e.target.value)} className="h-11 rounded-lg border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" required={field.required}/>}</label>)}</div>
      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-border p-6 md:px-8"><button disabled={step===0} onClick={()=>setStep(s=>s-1)} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border px-4 text-sm font-medium disabled:opacity-40"><ChevronLeft className="size-4"/>Previous</button><div className="text-xs text-muted-foreground">{complete} of {required.length} required fields completed</div>{step<sections.length-1?<button onClick={()=>setStep(s=>s+1)} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground">Next<ChevronRight className="size-4"/></button>:<button onClick={generatePdf} className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground"><Download className="size-4"/>Generate PDF</button>}</footer></section>
    </div><footer className="mx-auto flex max-w-7xl items-center gap-2 px-5 pb-8 text-xs text-muted-foreground lg:px-8"><FileText className="size-4"/>No answers are uploaded to a server. The final PDF downloads directly to this device.</footer>
  </main>
}
