import Fastify from 'fastify'
import cors from '@fastify/cors'
import cookie from '@fastify/cookie'
import helmet from '@fastify/helmet'
import rateLimit from '@fastify/rate-limit'
import jwt from '@fastify/jwt'
import swagger from '@fastify/swagger'
import swaggerUi from '@fastify/swagger-ui'
import { and, desc, eq, ilike, isNull, or, sql } from 'drizzle-orm'
import { z } from 'zod'
import { writeAudit } from './audit.js'
import { checkDatabase, db } from './db/index.js'
import { auditLog, companySettings, declarationLines, declarations, masterRecords, numberSequences, refreshSessions, roles, users, workflowEvents } from './db/schema.js'
import { authenticate, authorize, hashToken, issueSession, passwordSchema, rotateSession, verifyPassword, type AuthUser } from './security.js'
import { calculateDutyAndVat, nextState, states, type DeclarationState } from './domain/workflow.js'
import operationsRoutes from './routes/operations.js'

const app=Fastify({logger:true,requestIdHeader:'x-request-id',trustProxy:true})
await app.register(helmet)
await app.register(cookie)
await app.register(cors,{origin:(process.env.CORS_ORIGIN??'http://localhost:3000').split(','),credentials:true})
await app.register(rateLimit,{max:200,timeWindow:'1 minute'})
await app.register(jwt,{secret:process.env.JWT_ACCESS_SECRET??'development-secret-change-in-production'})
await app.register(swagger,{openapi:{info:{title:'EURO TROUSERS Customs API',version:'1.0.0'},security:[{bearerAuth:[]}],components:{securitySchemes:{bearerAuth:{type:'http',scheme:'bearer',bearerFormat:'JWT'}}}}})
await app.register(swaggerUi,{routePrefix:'/api/docs'})

const pageSchema=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),search:z.string().trim().optional(),archived:z.enum(['true','false','all']).default('false')})
const masterSchema=z.object({type:z.string().min(2).max(40),code:z.string().min(1).max(60),nameEn:z.string().min(1).max(240),nameAr:z.string().max(240).optional(),metadata:z.record(z.string(),z.unknown()).default({})})
const lineSchema=z.object({itemId:z.string().uuid().optional(),hsCodeId:z.string().uuid().optional(),descriptionEn:z.string().min(1),descriptionAr:z.string().optional(),quantity:z.number().positive(),uom:z.string().min(1),unitPrice:z.number().nonnegative(),dutyRate:z.number().min(0).max(100).default(5),exempt:z.boolean().default(false)})
const declarationSchema=z.object({kind:z.enum(['IMPORT','EXPORT','TRANSFER']),transferType:z.enum(['FZ_TO_FZ','FZ_TO_MAINLAND','MAINLAND_TO_FZ','TEMPORARY','RETURN']).optional(),declarationDate:z.coerce.date().optional(),shipmentRef:z.string().max(80).optional(),invoiceNumber:z.string().max(80).optional(),partnerId:z.string().uuid().optional(),transportMode:z.enum(['SEA','AIR','LAND','COURIER']),currency:z.string().length(3).default('AED'),exchangeRate:z.number().positive().default(1),saifReference:z.string().max(100).optional(),dueBackAt:z.coerce.date().optional(),remarks:z.string().optional(),vatExempt:z.boolean().default(false),lines:z.array(lineSchema).min(1)})

app.get('/health',async(_request,reply)=>{try{return{status:'ok',service:'customs-api',database:(await checkDatabase())?'connected':'unknown',time:new Date().toISOString()}}catch{return reply.code(503).send({status:'degraded',service:'customs-api',database:'unavailable'})}})
app.post('/api/auth/login',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(request,reply)=>{const input=z.object({email:z.string().email(),password:z.string().min(1)}).parse(request.body);const [record]=await db.select({id:users.id,email:users.email,passwordHash:users.passwordHash,displayName:users.displayName,role:roles.name,failedAttempts:users.failedAttempts,lockedUntil:users.lockedUntil,active:users.active}).from(users).innerJoin(roles,eq(users.roleId,roles.id)).where(eq(users.email,input.email.toLowerCase())).limit(1);if(!record||!record.active||record.lockedUntil&&record.lockedUntil>new Date()||!await verifyPassword(input.password,record.passwordHash)){if(record){const attempts=record.failedAttempts+1;await db.update(users).set({failedAttempts:attempts,lockedUntil:attempts>=5?new Date(Date.now()+15*60_000):null}).where(eq(users.id,record.id))}return reply.code(401).send({error:'INVALID_CREDENTIALS'})}await db.update(users).set({failedAttempts:0,lockedUntil:null}).where(eq(users.id,record.id));const session=await issueSession(app,{sub:record.id,email:record.email,role:record.role});reply.setCookie('refresh_token',session.refreshToken,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/api/auth',expires:session.expiresAt});return{accessToken:session.accessToken,user:{id:record.id,name:record.displayName,email:record.email,role:record.role}}})
app.post('/api/auth/refresh',async(request,reply)=>{const token=request.cookies.refresh_token;if(!token)return reply.code(401).send({error:'REFRESH_REQUIRED'});const session=await rotateSession(app,token);if(!session)return reply.code(401).clearCookie('refresh_token',{path:'/api/auth'}).send({error:'INVALID_REFRESH'});reply.setCookie('refresh_token',session.refreshToken,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/api/auth',expires:session.expiresAt});return{accessToken:session.accessToken}})
app.post('/api/auth/logout',async(request,reply)=>{const token=request.cookies.refresh_token;if(token)await db.update(refreshSessions).set({revokedAt:new Date()}).where(eq(refreshSessions.tokenHash,hashToken(token)));return reply.clearCookie('refresh_token',{path:'/api/auth'}).code(204).send()})
app.get('/api/auth/me',{preHandler:authenticate},async request=>{const actor=request.user as AuthUser;const [record]=await db.select({id:users.id,name:users.displayName,email:users.email,role:roles.name}).from(users).innerJoin(roles,eq(users.roleId,roles.id)).where(eq(users.id,actor.sub)).limit(1);return record})

app.get('/api/settings/company',{preHandler:authorize(app,'administration','view')},async()=>{const [settings]=await db.select().from(companySettings).limit(1);return settings})
app.patch('/api/settings/company',{preHandler:authorize(app,'administration','edit')},async(request)=>{const input=z.object({nameEn:z.string().min(1).optional(),nameAr:z.string().min(1).optional(),trn:z.string().min(1).optional(),addressEn:z.string().min(1).optional(),addressAr:z.string().optional(),approvalThresholdAed:z.string().optional(),vatRate:z.string().optional(),holdEscalationDays:z.number().int().positive().optional(),containerAlertDays:z.number().int().positive().optional()}).parse(request.body);const [before]=await db.select().from(companySettings).limit(1);if(!before)throw Object.assign(new Error('SETTINGS_NOT_FOUND'),{statusCode:404});const [after]=await db.update(companySettings).set({...input,updatedAt:new Date()}).where(eq(companySettings.id,before.id)).returning();await writeAudit(request,{action:'UPDATE',entity:'company_settings',entityId:before.id,before,after});return after})

app.get('/api/masters',{preHandler:authorize(app,'masters','view')},async(request)=>{const query=pageSchema.extend({type:z.string().optional()}).parse(request.query);const filters=[query.type?eq(masterRecords.type,query.type):undefined,query.archived==='false'?isNull(masterRecords.archivedAt):query.archived==='true'?sql`${masterRecords.archivedAt} is not null`:undefined,query.search?or(ilike(masterRecords.code,`%${query.search}%`),ilike(masterRecords.nameEn,`%${query.search}%`),ilike(masterRecords.nameAr,`%${query.search}%`)):undefined].filter(Boolean);const where=filters.length?and(...filters):undefined;const data=await db.select().from(masterRecords).where(where).orderBy(masterRecords.type,masterRecords.code).limit(query.pageSize).offset((query.page-1)*query.pageSize);const [count]=await db.select({value:sql<number>`count(*)`}).from(masterRecords).where(where);return{data,total:Number(count?.value??0),page:query.page,pageSize:query.pageSize}})
app.post('/api/masters',{preHandler:authorize(app,'masters','create')},async(request,reply)=>{const input=masterSchema.parse(request.body);const [created]=await db.insert(masterRecords).values(input).returning();await writeAudit(request,{action:'CREATE',entity:'master_record',entityId:created!.id,after:created});return reply.code(201).send(created)})
app.patch('/api/masters/:id',{preHandler:authorize(app,'masters','edit')},async(request)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const input=masterSchema.partial().parse(request.body);const [before]=await db.select().from(masterRecords).where(eq(masterRecords.id,id)).limit(1);if(!before)throw Object.assign(new Error('MASTER_NOT_FOUND'),{statusCode:404});const [after]=await db.update(masterRecords).set({...input,updatedAt:new Date()}).where(eq(masterRecords.id,id)).returning();await writeAudit(request,{action:'UPDATE',entity:'master_record',entityId:id,before,after});return after})
app.post('/api/masters/:id/archive',{preHandler:authorize(app,'masters','archive')},async(request)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const [after]=await db.update(masterRecords).set({archivedAt:new Date(),updatedAt:new Date()}).where(eq(masterRecords.id,id)).returning();if(!after)throw Object.assign(new Error('MASTER_NOT_FOUND'),{statusCode:404});await writeAudit(request,{action:'ARCHIVE',entity:'master_record',entityId:id,after});return after})
app.post('/api/masters/:id/restore',{preHandler:authorize(app,'masters','restore')},async(request)=>{const {id}=z.object({id:z.string().uuid()}).parse(request.params);const [after]=await db.update(masterRecords).set({archivedAt:null,updatedAt:new Date()}).where(eq(masterRecords.id,id)).returning();if(!after)throw Object.assign(new Error('MASTER_NOT_FOUND'),{statusCode:404});await writeAudit(request,{action:'RESTORE',entity:'master_record',entityId:id,after});return after})

async function nextNumber(kind:'IMPORT'|'EXPORT'|'TRANSFER'){const prefix=kind==='IMPORT'?'IMP':kind==='EXPORT'?'EXP':'TRF',year=new Date().getUTCFullYear();const result=await db.transaction(async tx=>{await tx.insert(numberSequences).values({type:prefix,year,value:0}).onConflictDoNothing();const [row]=await tx.update(numberSequences).set({value:sql`${numberSequences.value}+1`}).where(and(eq(numberSequences.type,prefix),eq(numberSequences.year,year))).returning({value:numberSequences.value});return row!.value});return`${prefix}-${year}-${String(result).padStart(4,'0')}`}
app.get('/api/declarations',{preHandler:authorize(app,'declarations','view')},async(request)=>{const query=pageSchema.extend({status:z.enum(states).optional(),kind:z.enum(['IMPORT','EXPORT','TRANSFER']).optional()}).parse(request.query);const where=and(query.status?eq(declarations.status,query.status):undefined,query.kind?eq(declarations.kind,query.kind):undefined,query.archived==='false'?isNull(declarations.archivedAt):undefined,query.search?or(ilike(declarations.number,`%${query.search}%`),ilike(declarations.shipmentRef,`%${query.search}%`),ilike(declarations.invoiceNumber,`%${query.search}%`)):undefined);const data=await db.select().from(declarations).where(where).orderBy(desc(declarations.declarationDate)).limit(query.pageSize).offset((query.page-1)*query.pageSize);const [count]=await db.select({value:sql<number>`count(*)`}).from(declarations).where(where);return{data,total:Number(count?.value??0),page:query.page,pageSize:query.pageSize}})
app.get('/api/declarations/:id',{preHandler:authorize(app,'declarations','view')},async(request)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const [record]=await db.select().from(declarations).where(eq(declarations.id,id)).limit(1);if(!record)throw Object.assign(new Error('DECLARATION_NOT_FOUND'),{statusCode:404});const lines=await db.select().from(declarationLines).where(eq(declarationLines.declarationId,id));const history=await db.select().from(workflowEvents).where(eq(workflowEvents.declarationId,id)).orderBy(workflowEvents.createdAt);return{...record,lines,history}})
app.post('/api/declarations',{preHandler:authorize(app,'declarations','create')},async(request,reply)=>{const input=declarationSchema.parse(request.body),actor=request.user as AuthUser;if(input.kind==='TRANSFER'&&!input.transferType)throw new z.ZodError([{code:'custom',path:['transferType'],message:'Transfer type is required'}]);if(input.transferType==='TEMPORARY'&&!input.dueBackAt)throw new z.ZodError([{code:'custom',path:['dueBackAt'],message:'Due-back date is required'}]);const number=await nextNumber(input.kind),originalValue=input.lines.reduce((sum,line)=>sum+line.quantity*line.unitPrice,0),valueAed=originalValue*input.exchangeRate;const totals=input.lines.reduce((sum,line)=>{const result=calculateDutyAndVat(line.quantity*line.unitPrice*input.exchangeRate,line.dutyRate,5,line.exempt,input.vatExempt);return{duty:sum.duty+result.dutyAed,vat:sum.vat+result.vatAed}},{duty:0,vat:0});const created=await db.transaction(async tx=>{const [record]=await tx.insert(declarations).values({number,kind:input.kind,transferType:input.transferType,declarationDate:input.declarationDate,shipmentRef:input.shipmentRef,invoiceNumber:input.invoiceNumber,partnerId:input.partnerId,transportMode:input.transportMode,currency:input.currency.toUpperCase(),exchangeRate:String(input.exchangeRate),originalValue:String(originalValue),valueAed:String(valueAed),dutyAed:String(totals.duty),vatAed:String(totals.vat),saifReference:input.saifReference,dueBackAt:input.dueBackAt,remarks:input.remarks,createdBy:actor.sub}).returning();await tx.insert(declarationLines).values(input.lines.map(line=>({...line,declarationId:record!.id,quantity:String(line.quantity),unitPrice:String(line.unitPrice),dutyRate:String(line.dutyRate)})));return record!});await writeAudit(request,{action:'CREATE',entity:'declaration',entityId:created.id,after:created});return reply.code(201).send(created)})
app.post('/api/declarations/:id/transition',{preHandler:authorize(app,'declarations','approve')},async(request)=>{const{id}=z.object({id:z.string().uuid()}).parse(request.params);const input=z.object({action:z.enum(['NEXT','REJECT','HOLD','RELEASE','CANCEL','INSPECTION']),reason:z.string().trim().optional(),saifReference:z.string().trim().optional(),previousState:z.enum(states).optional()}).parse(request.body);const [before]=await db.select().from(declarations).where(eq(declarations.id,id)).limit(1);if(!before)throw Object.assign(new Error('DECLARATION_NOT_FOUND'),{statusCode:404});if(['REJECT','HOLD','CANCEL'].includes(input.action)&&!input.reason)throw new z.ZodError([{code:'custom',path:['reason'],message:'Reason is required'}]);let target:DeclarationState;if(input.action==='REJECT')target='REJECTED';else if(input.action==='HOLD')target='ON_HOLD';else if(input.action==='CANCEL')target='CANCELLED';else if(input.action==='INSPECTION')target='UNDER_INSPECTION';else if(input.action==='RELEASE'){if(before.status!=='ON_HOLD'||!input.previousState)throw Object.assign(new Error('PREVIOUS_STATE_REQUIRED'),{statusCode:400});target=input.previousState}else target=nextState(before.status as DeclarationState,{dutyAed:Number(before.dutyAed),vatAed:Number(before.vatAed),valueAed:Number(before.valueAed),approvalThresholdAed:Number(process.env.APPROVAL_THRESHOLD_AED??100000)});if(target==='SUBMITTED'&&!input.saifReference)throw Object.assign(new Error('SAIF_REFERENCE_REQUIRED'),{statusCode:400});const actor=request.user as AuthUser;const [after]=await db.update(declarations).set({status:target,saifReference:input.saifReference??before.saifReference,updatedAt:new Date()}).where(eq(declarations.id,id)).returning();await db.insert(workflowEvents).values({declarationId:id,fromState:before.status,toState:target,reason:input.reason,actorId:actor.sub});await writeAudit(request,{action:'STATE_TRANSITION',entity:'declaration',entityId:id,before:{status:before.status},after:{status:target,reason:input.reason}});return after})

app.get('/api/audit',{preHandler:authorize(app,'audit','view')},async(request)=>{const query=pageSchema.extend({entity:z.string().optional(),entityId:z.string().optional()}).parse(request.query);const where=and(query.entity?eq(auditLog.entity,query.entity):undefined,query.entityId?eq(auditLog.entityId,query.entityId):undefined);const data=await db.select().from(auditLog).where(where).orderBy(desc(auditLog.createdAt)).limit(query.pageSize).offset((query.page-1)*query.pageSize);return{data,page:query.page,pageSize:query.pageSize}})
app.get('/api/calculations/duty',{preHandler:authenticate},async request=>{const input=z.object({valueAed:z.coerce.number().nonnegative(),dutyRate:z.coerce.number().min(0).max(100).default(5),vatRate:z.coerce.number().min(0).max(100).default(5),exempt:z.coerce.boolean().default(false),vatExempt:z.coerce.boolean().default(false)}).parse(request.query);return calculateDutyAndVat(input.valueAed,input.dutyRate,input.vatRate,input.exempt,input.vatExempt)})
await app.register(operationsRoutes,{prefix:'/api'})
app.get('/api/modules',{preHandler:authenticate},async()=>({modules:['Customs Master','Import Declaration','Export Declaration','Transfer Declaration','Duty, VAT & Finance','Customs Documents','Container Management','Inspection & Hold','Clearance','Stock Reconciliation','Reports','Integration'],roles:['System Administrator','Customs Manager','Documentation Officer','Data Entry Officer','Warehouse Officer','Finance Officer','Logistics Officer','General Manager','Viewer','Auditor']}))

app.setErrorHandler((error,request,reply)=>{request.log.error(error);const validation=error instanceof z.ZodError,status=(error as {statusCode?:number}).statusCode??(validation?400:500);reply.code(status).send({error:validation?'VALIDATION_ERROR':status===403?'FORBIDDEN':status===401?'UNAUTHORIZED':status===404?'NOT_FOUND':'REQUEST_ERROR',message:validation?'Request validation failed':status>=500?'Unexpected server error':(error as Error).message,requestId:request.id,issues:validation?error.issues:undefined})})
await app.listen({port:Number(process.env.PORT??4000),host:'0.0.0.0'})
