import type { FastifyPluginAsync } from 'fastify'
import { and, desc, eq, isNull, sql } from 'drizzle-orm'
import { z } from 'zod'
import { db } from '../db/index.js'
import { declarations, documents, financeRecords, operationalRecords, reconciliations, stockLedger } from '../db/schema.js'
import { authorize } from '../security.js'
import { writeAudit } from '../audit.js'

const uuidParam=z.object({id:z.string().uuid()})
const listQuery=z.object({type:z.string().optional(),status:z.string().optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25)})
const operationsRoutes:FastifyPluginAsync=async app=>{
 app.get('/finance',{preHandler:authorize(app,'finance','view')},async request=>{const q=listQuery.parse(request.query),where=and(q.type?eq(financeRecords.type,q.type):undefined,q.status?eq(financeRecords.status,q.status):undefined,isNull(financeRecords.archivedAt));const data=await db.select().from(financeRecords).where(where).orderBy(desc(financeRecords.createdAt)).limit(q.pageSize).offset((q.page-1)*q.pageSize);return{data,page:q.page,pageSize:q.pageSize}})
 app.post('/finance',{preHandler:authorize(app,'finance','create')},async(request,reply)=>{const input=z.object({type:z.enum(['BANK_GUARANTEE','DUTY_REFUND','DEPOSIT','EXCHANGE_RATE']),number:z.string().min(1),status:z.string().min(1),amount:z.number().nonnegative(),utilized:z.number().nonnegative().default(0),currency:z.string().length(3).default('AED'),declarationId:z.string().uuid().optional(),issuedAt:z.coerce.date().optional(),expiresAt:z.coerce.date().optional(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(request.body);if(input.utilized>input.amount)throw Object.assign(new Error('UTILIZATION_EXCEEDS_AMOUNT'),{statusCode:400});const [record]=await db.insert(financeRecords).values({...input,amount:String(input.amount),utilized:String(input.utilized)}).returning();await writeAudit(request,{action:'CREATE',entity:'finance_record',entityId:record!.id,after:record});return reply.code(201).send(record)})
 app.post('/finance/:id/approve',{preHandler:authorize(app,'finance','approve')},async request=>{const{id}=uuidParam.parse(request.params);const [before]=await db.select().from(financeRecords).where(eq(financeRecords.id,id)).limit(1);if(!before)throw Object.assign(new Error('FINANCE_RECORD_NOT_FOUND'),{statusCode:404});const [after]=await db.update(financeRecords).set({status:'APPROVED',updatedAt:new Date()}).where(eq(financeRecords.id,id)).returning();await writeAudit(request,{action:'APPROVE',entity:'finance_record',entityId:id,before,after});return after})
 app.get('/operations',{preHandler:authorize(app,'containers','view')},async request=>{const q=listQuery.parse(request.query),where=and(q.type?eq(operationalRecords.type,q.type):undefined,q.status?eq(operationalRecords.status,q.status):undefined,isNull(operationalRecords.archivedAt));const data=await db.select().from(operationalRecords).where(where).orderBy(desc(operationalRecords.createdAt)).limit(q.pageSize).offset((q.page-1)*q.pageSize);return{data,page:q.page,pageSize:q.pageSize}})
 app.post('/operations',{preHandler:authorize(app,'containers','create')},async(request,reply)=>{const input=z.object({type:z.enum(['SHIPMENT','CONTAINER','INSPECTION','HOLD','CLEARANCE','RELEASE_ORDER','EXIT_PASS','GATE_PASS','WAREHOUSE_RECEIPT']),number:z.string().min(1),status:z.string().min(1),declarationId:z.string().uuid().optional(),ownerId:z.string().uuid().optional(),dueAt:z.coerce.date().optional(),dailyCharge:z.number().nonnegative().optional(),metadata:z.record(z.string(),z.unknown()).default({})}).parse(request.body);const [record]=await db.insert(operationalRecords).values({...input,dailyCharge:input.dailyCharge===undefined?undefined:String(input.dailyCharge)}).returning();await writeAudit(request,{action:'CREATE',entity:'operational_record',entityId:record!.id,after:record});return reply.code(201).send(record)})
 app.patch('/operations/:id/status',{preHandler:authorize(app,'clearance','edit')},async request=>{const{id}=uuidParam.parse(request.params),input=z.object({status:z.string().min(1),metadata:z.record(z.string(),z.unknown()).optional()}).parse(request.body);const [before]=await db.select().from(operationalRecords).where(eq(operationalRecords.id,id)).limit(1);if(!before)throw Object.assign(new Error('OPERATION_NOT_FOUND'),{statusCode:404});const [after]=await db.update(operationalRecords).set({status:input.status,metadata:input.metadata??before.metadata,completedAt:['CLOSED','CLEARED','RELEASED','USED'].includes(input.status)?new Date():before.completedAt,updatedAt:new Date()}).where(eq(operationalRecords.id,id)).returning();await writeAudit(request,{action:'STATUS_CHANGE',entity:'operational_record',entityId:id,before,after});return after})
 app.get('/documents',{preHandler:authorize(app,'documents','view')},async request=>{const q=z.object({entityType:z.string().optional(),entityId:z.string().uuid().optional()}).parse(request.query);return{data:await db.select().from(documents).where(and(q.entityType?eq(documents.entityType,q.entityType):undefined,q.entityId?eq(documents.entityId,q.entityId):undefined)).orderBy(desc(documents.createdAt))}})
 app.get('/stock/ledger',{preHandler:authorize(app,'stock','view')},async()=>{const data=await db.select({itemId:stockLedger.itemId,balance:sql<string>`sum(case when ${stockLedger.direction}='IN' then ${stockLedger.quantity} else -${stockLedger.quantity} end)`,movements:sql<number>`count(*)`}).from(stockLedger).groupBy(stockLedger.itemId);return{data}})
 app.get('/stock/reconciliations',{preHandler:authorize(app,'stock','view')},async()=>({data:await db.select().from(reconciliations).orderBy(desc(reconciliations.createdAt))}))
 app.post('/stock/reconciliations',{preHandler:authorize(app,'stock','create')},async(request,reply)=>{const input=z.object({period:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),customsTotal:z.number(),warehouseTotal:z.number()}).parse(request.body);const [record]=await db.insert(reconciliations).values({period:input.period,customsTotal:String(input.customsTotal),warehouseTotal:String(input.warehouseTotal),variance:String(input.warehouseTotal-input.customsTotal)}).returning();await writeAudit(request,{action:'CREATE',entity:'reconciliation',entityId:record!.id,after:record});return reply.code(201).send(record)})
 app.get('/dashboard',async()=>{const [pending]=await db.select({count:sql<number>`count(*)`}).from(declarations).where(sql`${declarations.status} like '%PENDING'`),[holds]=await db.select({count:sql<number>`count(*)`}).from(declarations).where(eq(declarations.status,'ON_HOLD')),[clearances]=await db.select({count:sql<number>`count(*)`}).from(operationalRecords).where(and(eq(operationalRecords.type,'CLEARANCE'),sql`${operationalRecords.status} not in ('CLOSED','CANCELLED')`));return{kpis:{pendingApprovals:Number(pending?.count??0),holds:Number(holds?.count??0),activeClearances:Number(clearances?.count??0)},generatedAt:new Date().toISOString()}})
}
export default operationsRoutes
